name: "build"
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        java: [ "17" ]
        os: [ "ubuntu-latest" ]
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "validate gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v2"
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"
      - name: "configure git"
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: "apply patches"
        run: "git submodule update --init && ./gradlew applyPatches"
      - name: "build"
        run: "cd patched-loom && ./gradlew build -x test"
      - name: "publish"
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev/') }}
        run: "cd patched-loom && ./gradlew publish -x test"
        env:
          JMP_REPO_USER: ${{ secrets.JMP_REPO_USER }}
          JMP_REPO_PASSWORD: ${{ secrets.JMP_REPO_PASSWORD }}
