name: "build"
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        buildDir: [ "quiet-fabric-loom", "quiet-architectury-loom" ]
        java: [ "17" ]
        os: [ "ubuntu-latest" ]
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v4"
      - name: "validate gradle wrapper"
        uses: gradle/wrapper-validation-action@v2
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v4"
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"
      - name: "configure git"
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: "setup gradle"
        uses: gradle/actions/setup-gradle@v3
      - name: "apply patches"
        run: "git submodule update --init && ./gradlew applyPatches"
      - name: "build"
        run: "cd ${{ matrix.buildDir }} && ./gradlew build -x check"
      - name: "publish"
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev/') || startsWith(github.ref, 'refs/heads/exp/') }}
        run: "cd ${{ matrix.buildDir }} && ./gradlew publish -x check"
        env:
          JMP_REPO_USER: ${{ secrets.JMP_REPO_USER }}
          JMP_REPO_PASSWORD: ${{ secrets.JMP_REPO_PASSWORD }}
